### ISSUE TITLE
Ejercicio finalizado - Ana Heredero Gómez

### ISSUE THREAD

**Issue by anaheredero** [anaheredero/testsim#1]
Hola Tomás, he subido el script del ejercicio finalizado que tiene por nombre: **pipeline_testim**, en el repositorio "scripts".
Aparentemente, sale todo correcto con un 91,8% de alineamiento.

Un saludo!

**Comment by tdido** [comment]
Hola Ana.

Está muy bien, el script funciona perfectamente. Cierro la incidencia, pero te dejo unos comentarios para que tengas en cuenta:

- En lugar de pegar el contenido del script "analyse_sample" dentro del nuevo script, lo ideal hubiera sido llamar a "analyse_sample" dentro del loop. Algo así:
```shell
for sampleid in $(ls data/*.fastq.gz | cut -d "_" -f1 | sed 's:data/::' | sort | uniq)
do
    bash scripts/analyse_sample.sh $sampleid
done
```
- Fijate que cuando creás los directorios de cutadapt no pusiste el "-p" a mkdir, por eso da errores. El script continua, pero podría dar problemas si lo combinaras con otros.
- Te faltó exportar el ambiente conda y subir al repo el archivo resultante (esto se hace manualmente, fuera de los scripts. El código está en el README).
- No conviene llamar a software interactivo como firefox desde un pipeline, con lo cual el comando que abre el reporte de multiqc mejor dejarlo para que lo ejecute a mano quien mire los datos.

**Comment by anaheredero** [comment]
Vale, genial. Tomo nota de las demás observaciones.
Se me olvidó subir al repositorio el ambiente conda. Ya lo subí a mi
repositorio "envs".

Muchas gracias Tomás!
